name: Update GeoLite

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: 0 0 */3 * *

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - name: Download GeoLite.mmdb
      run: |
        mkdir -p Xtream_Update
        wget -nv -O- "https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-ASN&license_key=${{ secrets.LICENSE_KEY_MAXMIND }}&suffix=tar.gz" | tar zxv
        wget -nv -O- "https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-City&license_key=${{ secrets.LICENSE_KEY_MAXMIND }}&suffix=tar.gz" | tar zxv
        wget -nv -O- "https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-Country&license_key=${{ secrets.LICENSE_KEY_MAXMIND }}&suffix=tar.gz" | tar zxv   
        cp -v GeoLite*/*.mmdb Xtream_Update
        echo "TAG_NAME=$(date +"%d.%m.%y")" >> $GITHUB_ENV
    
    - name: Generate hashes.md5
      run: |
        cd Xtream_Update
        md5sum *.mmdb > hashes.md5
        echo "Generated hashes:"
        cat hashes.md5
    
    - name: Upload to Releases
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.TAG_NAME }}
        body: ${{ env.TAG_NAME }}
        files: |
          Xtream_Update/*.mmdb
          Xtream_Update/hashes.md5

    - name: Remove old Releases
      uses: dev-drprasad/delete-older-releases@master
      with:
        keep_latest: 2
        delete_tags: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@main
      with:
        retain_days: 0
        keep_minimum_runs: 2